### ISSUE TITLE
Mejoras propuestas 19/05/2016

### ISSUE THREAD

**Issue by jaimelaborda** [makers-upv/web#1]
- [ ] Añadir apartado para poner la **firma en la redacción** (lo podemos hacer desde el docs pero sería mas mejor que estuviera incluido en el formato.
- [ ] Posibilidad de **añadir "vídeo de youtube"**  en vez de foto o flickr en el artículo.
- [ ] Posibilidad de **combinar vídeo y fotos**.
- [ ] Añadir **categoría Ciencia** para artículos de corte más científico
- [ ] Relacionado  con esto.. estamos pensando en subir papers.. quizás estaría guay **añadir integración con un visor de documentos del tipo Isuu**
- [ ] Añadir al excel una pestaña para subir el **doc en inglés**. Para los docs en inglés aparecería en el artículo arriba a la derecha el típico (EN/ES). Habrá pocos, pero creemos que deberían estar como solo un artículo en la principal

**Comment by franciscop** [comment]
Añadidos como issues individuales (mucho mejor a la hora de ir cerrandolos)
